LogFile /Users/mac/Downloads/ltalms/logs/clamd.log
LogTime yes
LogRotate yes
PidFile /Users/mac/Downloads/ltalms/tmp/clamd.pid
TemporaryDirectory /Users/mac/Downloads/ltalms/tmp
DatabaseDirectory /Users/mac/Downloads/ltalms/tmp/clamav-db
TCPSocket 3310
TCPAddr 127.0.0.1
EnableShutdownCommand no
StreamMaxLength 11M
ReadTimeout 30
CommandReadTimeout 5
MaxThreads 4
MaxQueue 8
